name: capture_your_life
description: AI-powered mobile app for creating stickers and avatars from photos.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  http: ^1.1.0
  image_picker: ^1.0.4
  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1
  firebase_auth: ^6.5.1
  shared_preferences: ^2.2.2
  dio: ^5.3.1
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
